import { createElement } from 'lwc';
import Datatable_Actions_Inline_Edit_D25 from 'c/datatable_Actions_Inline_Edit_D25';

describe('c-datatable-actions-inline-edit-d-25', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-datatable-actions-inline-edit-d-25', {
            is: Datatable_Actions_Inline_Edit_D25
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});