import { createElement } from 'lwc';
import FlowLwcCmp_D32 from 'c/flowLwcCmp_D32';

describe('c-flow-lwc-cmp-d-32', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-flow-lwc-cmp-d-32', {
            is: FlowLwcCmp_D32
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});