public class Calculator {
    public integer add(integer x, integer y){
        integer z = x + y;
        return z;
    }
    public integer sub(integer x, integer y){
        integer z = x - y;
        return z;
    }
    public integer multi(integer x , integer y){
        integer z = x*y;
        return z;
    }
    public integer div(integer x , integer y){
        integer z = x/y;
        return z;
    }
}