public class simpleCalculator {
    public void calci(){
        
        integer x = 10;
        integer y = 10;
        integer Add = x + y;
        integer Sub = x-y;
        integer Multiply = x*y;
        integer Division = x / y;
        
        System.debug('Add=' +Add);
        System.debug('Sub=' +Sub);
        System.debug('Multiply=' +Multiply);
        System.debug('Division=' +Division);
    }
}